[package]
name = "chonk"
version = "0.1.0"
edition = "2021"

[lints.rust]
unsafe_code = "forbid"
unused_results = "forbid"
# missing_debug_implementations = "warn"
# missing_docs = "warn"

[lints.clippy]
pedantic = "warn"
copy_iterator = "allow"

[dependencies]
